export const metadata = {
  title: 'Senaei',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl">
      <head>
        <link href="./output.css" rel="stylesheet" />
        {/* <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" /> */}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" />
        
      </head>
      <body style={{margin: "0", padding: "0" }}>
        
        {children}
        
      </body>
    </html>
  )
}
